import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import TechnologyCard from "../components/TechnologyCard/TechnologyCard";
import NavBar from "../components/NavBar/NavBar";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from Up on Jacks" });
  const techObj = [
    { name: "NextJS", description: "The React framework for production", documentation: "https://nextjs.org/" }, { name: "NextJS", description: "The React framework for production", documentation: "https://nextjs.org/" }, { name: "NextJS", description: "The React framework for production", documentation: "https://nextjs.org/" }, { name: "NextJS", description: "The React framework for production", documentation: "https://nextjs.org/" }, { name: "NextJS", description: "The React framework for production", documentation: "https://nextjs.org/" }, { name: "NextJS", description: "The React framework for production", documentation: "https://nextjs.org/" }
  ];
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <p className="text-2xl text-gray-700">This stack uses:</p>
        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-3 lg:w-2/3">
          {techObj.map(data =>
            <TechnologyCard
              name={data.name}
              description={data.description}
              documentation={data.documentation}
            />
          )}
        </div>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {sessionData && (
        <p className="text-2xl text-blue-500">
          Logged in as {sessionData?.user?.name}
        </p>
      )}
    </div>
  );
};


